---
name: handle-inquiries-2fa
description: Notify inquiries
enabled: false

trigger:
  type: core.st2.generic.inquiry

criteria:
    trigger.route:
        type: "iequals"
        pattern : "2fa"

action:
  ref: examples.handle-inquiries-2fa
  parameters:
    inquiry_data: "{{ trigger }}"
